#!/usr/bin/env python3
"""
Retro-link textual mentions of modeled entities to wiki-links.

Walks the workspace, discovers entities from frontmatter (`type` of
client-context, partner-context, person, service, topic, project-brief),
then scans all markdown files for plain-text mentions of those entities
and proposes turning them into [[Wiki Links]].

Conservative by design:
- Default mode is --dry-run, prints a unified diff per file.
- Only mentions whose canonical name is at least 4 chars and not in a
  stop-list of common words are considered.
- Skips text inside code fences (``` blocks), inline backticks, existing
  wiki-links, markdown links, URLs, and email quote lines starting with >.
- Skips frontmatter (only the body is rewritten).
- Skips email bodies under any `emails/` directory by default (high
  false-positive risk in quoted text). Use --include-emails to override.

Homonym handling:
- If an entity name resolves to more than one canonical note (e.g. a
  partner and a person both called "Alex Martin"), the mention is NOT
  auto-linked. It is reported in a separate ambiguities section so you
  can resolve manually.

Usage:
    python3 basic-memory/scripts/auto_link_entities.py --dry-run
    python3 basic-memory/scripts/auto_link_entities.py --apply
    python3 basic-memory/scripts/auto_link_entities.py --dry-run --include-emails
"""

from __future__ import annotations

import argparse
import difflib
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

import yaml

WORKSPACE = Path(__file__).resolve().parent.parent.parent
IGNORED_SEGMENTS = {".git", "node_modules", ".obsidian", ".claude"}
IGNORED_PATH_PREFIXES = (
    "templates/",
    "basic-memory/scripts/",
    "basic-memory/schemas/",
    "atlas/maps/",  # generated indexes, paths inside must stay literal
)

# Also skip files ending with -static.md anywhere (generated by generate_indexes.py).
IGNORED_FILENAME_SUFFIXES = ("-static.md",)

ENTITY_TYPES = {"client-context", "partner-context", "person", "service", "topic", "project-brief"}

# Names too generic to safely auto-link.
STOP_NAMES = {
    "personal", "internal", "client", "service", "design", "site", "audit",
    "ops", "tech", "business", "ai", "wcag", "seo", "wordpress",
}

WIKILINK_RE = re.compile(r"\[\[[^\]]+\]\]")
MARKDOWN_LINK_RE = re.compile(r"\[[^\]]+\]\([^)]+\)")
URL_RE = re.compile(r"https?://\S+")
INLINE_CODE_RE = re.compile(r"`[^`]*`")
EMAIL_RE = re.compile(r"\b[\w.+-]+@[\w.-]+\.\w{2,10}\b")
PERMALINK_RE = re.compile(r"^permalink:\s*\S+", re.MULTILINE)
# A path-like token: word chars + hyphens with at least one slash, also
# protects "my-project" and "my-project/sources/..." from auto-link.
PATH_TOKEN_RE = re.compile(r"\b[\w.-]+(?:[-/][\w.-]+)+\b")


@dataclass
class Entity:
    name: str  # canonical name (title)
    aliases: set[str] = field(default_factory=set)
    path: Path | None = None
    type: str = ""


@dataclass
class Mention:
    line_no: int
    raw_line: str
    matched: str
    canonical: str
    proposed_line: str


def is_ignored(rel: Path) -> bool:
    parts = rel.parts
    if any(p in IGNORED_SEGMENTS for p in parts):
        return True
    rel_str = rel.as_posix()
    if any(rel_str.startswith(p) for p in IGNORED_PATH_PREFIXES):
        return True
    if any(rel_str.endswith(s) for s in IGNORED_FILENAME_SUFFIXES):
        return True
    return False


def parse_frontmatter(text: str) -> tuple[dict, int]:
    """Return (frontmatter dict, body_start_line_index)."""
    if not text.startswith("---"):
        return {}, 0
    lines = text.split("\n")
    end = None
    for i in range(1, len(lines)):
        if lines[i] == "---":
            end = i
            break
    if end is None:
        return {}, 0
    fm_text = "\n".join(lines[1:end])
    try:
        fm = yaml.safe_load(fm_text) or {}
        if not isinstance(fm, dict):
            return {}, 0
    except yaml.YAMLError:
        return {}, 0
    return fm, end + 1


def discover_entities(root: Path) -> dict[str, list[Entity]]:
    """Return alias_lowercase -> list of Entities."""
    raw: dict[str, list[Entity]] = {}

    for path in root.rglob("*.md"):
        rel = path.relative_to(root)
        if is_ignored(rel):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        fm, _ = parse_frontmatter(text)
        t = str(fm.get("type", ""))
        if t not in ENTITY_TYPES:
            continue

        # Canonical name: prefer client/partner over title.
        canonical = (
            fm.get("client")
            or fm.get("partner")
            or fm.get("name")
            or fm.get("title")
        )
        if not canonical:
            continue
        canonical = str(canonical).strip()
        if len(canonical) < 4 or canonical.lower() in STOP_NAMES:
            continue

        entity = Entity(name=canonical, path=path, type=t)
        entity.aliases.add(canonical)
        # Optional alias fields.
        for alias_field in ("aliases", "also_known_as", "short_name"):
            v = fm.get(alias_field)
            if isinstance(v, str) and len(v) >= 4:
                entity.aliases.add(v.strip())
            elif isinstance(v, list):
                for x in v:
                    if isinstance(x, str) and len(x) >= 4:
                        entity.aliases.add(x.strip())

        for alias in entity.aliases:
            if alias.lower() in STOP_NAMES:
                continue
            raw.setdefault(alias.lower(), []).append(entity)

    return raw


def build_search_regex(aliases: list[str]) -> re.Pattern:
    """Sort by length desc to prefer longer match first."""
    sorted_aliases = sorted(set(aliases), key=len, reverse=True)
    escaped = [re.escape(a) for a in sorted_aliases]
    pattern = r"(?<![a-zA-ZÀ-ÿ\[])(?:" + "|".join(escaped) + r")(?![a-zA-ZÀ-ÿ\]])"
    return re.compile(pattern, re.IGNORECASE)


def strip_protected_regions(line: str) -> str:
    """Return a version of the line with protected regions blanked out
    (same length) so regex search doesn't match inside them.

    Protects: existing wiki-links, markdown links, URLs, inline code,
    email addresses, path-like tokens (with slashes or hyphens), and
    `permalink:` frontmatter lines.
    """
    blanked = line
    for pat in (
        WIKILINK_RE,
        MARKDOWN_LINK_RE,
        URL_RE,
        INLINE_CODE_RE,
        EMAIL_RE,
        PERMALINK_RE,
        PATH_TOKEN_RE,
    ):
        blanked = pat.sub(lambda m: " " * len(m.group(0)), blanked)
    return blanked


def in_code_fence(lines: list[str], idx: int) -> bool:
    """True if line idx is inside a triple-backtick code fence."""
    open_count = 0
    for i in range(idx):
        if lines[i].lstrip().startswith("```"):
            open_count += 1
    return open_count % 2 == 1


def scan_file(
    path: Path,
    text: str,
    by_alias: dict[str, list[Entity]],
    search_re: re.Pattern,
    include_emails: bool,
) -> tuple[list[Mention], list[Mention]]:
    """Return (linked, ambiguous)."""
    rel = path.relative_to(WORKSPACE)
    if not include_emails:
        if any(seg in {"emails", "mails", "mailings"} for seg in rel.parts):
            return [], []

    fm, body_start_idx = parse_frontmatter(text)
    self_canonical = str(
        fm.get("client") or fm.get("partner") or fm.get("name") or fm.get("title") or ""
    ).strip()

    lines = text.split("\n")
    linked: list[Mention] = []
    ambiguous: list[Mention] = []

    for i in range(body_start_idx, len(lines)):
        line = lines[i]
        if line.lstrip().startswith(">"):
            continue
        if in_code_fence(lines, i):
            continue

        scan_line = strip_protected_regions(line)
        new_line = line
        line_dirty = False

        for match in search_re.finditer(scan_line):
            alias_key = match.group(0).lower()
            entities = by_alias.get(alias_key, [])
            if not entities:
                continue
            # Skip self-mentions.
            entities_filtered = [e for e in entities if e.name != self_canonical]
            if not entities_filtered:
                continue

            unique_names = {e.name for e in entities_filtered}
            if len(unique_names) > 1:
                ambiguous.append(
                    Mention(
                        line_no=i + 1,
                        raw_line=line.rstrip(),
                        matched=match.group(0),
                        canonical=", ".join(sorted(unique_names)),
                        proposed_line="(skip, homonyms)",
                    )
                )
                continue

            canonical = entities_filtered[0].name
            original_text = line[match.start() : match.end()]
            replacement = f"[[{canonical}]]"
            if original_text.lower() != canonical.lower():
                replacement = f"[[{canonical}|{original_text}]]"

            proposed = new_line[: match.start()] + replacement + new_line[match.end() :]
            linked.append(
                Mention(
                    line_no=i + 1,
                    raw_line=line.rstrip(),
                    matched=original_text,
                    canonical=canonical,
                    proposed_line=proposed.rstrip(),
                )
            )
            new_line = proposed
            line_dirty = True
            # Only one auto-link per line in this version (avoid offset chaos).
            break

        if line_dirty:
            lines[i] = new_line

    return linked, ambiguous


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", default=True)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument(
        "--include-emails",
        action="store_true",
        help="Also rewrite mentions inside emails/mails directories.",
    )
    parser.add_argument(
        "--max-files",
        type=int,
        default=30,
        help="Max files shown in dry-run output (default: 30).",
    )
    args = parser.parse_args(argv)

    if args.apply:
        args.dry_run = False

    print("Discovering entities...", file=sys.stderr)
    by_alias = discover_entities(WORKSPACE)
    aliases = list(by_alias.keys())
    print(f"  {len(aliases)} alias(es) across {sum(len(v) for v in by_alias.values())} entity record(s).", file=sys.stderr)
    if not aliases:
        print("No entities discovered, nothing to do.")
        return 0
    search_re = build_search_regex(aliases)

    all_linked: dict[Path, list[Mention]] = {}
    all_ambiguous: dict[Path, list[Mention]] = {}
    new_texts: dict[Path, str] = {}

    print("Scanning files...", file=sys.stderr)
    for path in WORKSPACE.rglob("*.md"):
        rel = path.relative_to(WORKSPACE)
        if is_ignored(rel):
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        linked, ambiguous = scan_file(path, text, by_alias, search_re, args.include_emails)
        if linked:
            all_linked[path] = linked
            # Reconstruct the new file content by applying all linked mentions.
            new_lines = text.split("\n")
            for m in linked:
                new_lines[m.line_no - 1] = m.proposed_line
            new_texts[path] = "\n".join(new_lines)
        if ambiguous:
            all_ambiguous[path] = ambiguous

    total_links = sum(len(v) for v in all_linked.values())
    total_ambig = sum(len(v) for v in all_ambiguous.values())
    print(f"Would add {total_links} wiki-link(s) across {len(all_linked)} file(s).")
    print(f"Detected {total_ambig} ambiguous mention(s) (homonyms, manual review).")

    if args.dry_run:
        printed = 0
        for path, mentions in all_linked.items():
            if printed >= args.max_files:
                print(
                    f"\n... and {len(all_linked) - printed} more files. "
                    f"Re-run with --max-files {len(all_linked)} or --apply."
                )
                break
            rel = path.relative_to(WORKSPACE).as_posix()
            diff = "".join(
                difflib.unified_diff(
                    path.read_text(encoding="utf-8").splitlines(keepends=True),
                    new_texts[path].splitlines(keepends=True),
                    fromfile=rel,
                    tofile=rel,
                    n=1,
                )
            )
            print(diff)
            printed += 1

        if all_ambiguous:
            print("\n# Ambiguities (manual review required)")
            for path, mentions in all_ambiguous.items():
                rel = path.relative_to(WORKSPACE).as_posix()
                print(f"\n## {rel}")
                for m in mentions:
                    print(f"  L{m.line_no}: '{m.matched}' -> candidates: {m.canonical}")

        print("\nDry-run only. Re-run with --apply to write.")
        return 0

    # Apply mode.
    written = 0
    for path, new_text in new_texts.items():
        path.write_text(new_text, encoding="utf-8")
        written += 1
    print(f"Wrote {written} file(s).")
    if all_ambiguous:
        print(f"Skipped {total_ambig} ambiguous mention(s). Resolve manually.")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
